- project:
    templates:
      - openstack-python3-ussuri-jobs
      - openstack-lower-constraints-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pylint
    gate:
      jobs:
        - openstack-tox-pylint
