- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pylint
    gate:
      jobs:
        - openstack-tox-pylint
